module Rchess
  class CastlingFactory
    attr_reader field: Field

    def initialize: (Field field) -> nil

    def create_castlings: (Color king_color) -> Array[Castling]

    def create_king_side_castling: (Color king_color) -> Castling?

    def create_queen_side_castling: (Color king_color) -> Castling?

    private

    def create_castling: (CastlingPattern castling_pattern) -> Castling?
  end

end