module Rchess
  class PawnMoveCollectionFactory < MoveCollectionFactory
    def create: (Figure figure) -> MoveCollection

    private

    def create_vertical_moves: (Figure figure) -> Array[Move]

    def create_attacking_moves: (Figure figure) -> Array[Move]

    def check_transform: (Figure figure, Array[Move] moves) -> nil

    def check_taking_on_pass: (Array[Move] moves) -> nil
  end
end