module Rchess
  class Castling
    attr_reader king_move: Move

    attr_reader rook_move: Move

    attr_reader side: CastlingSide

    attr_reader though_position: Position

    attr_reader required_positions: Array[Position]

    attr_accessor prohibition: MoveProhibition

    def initialize: (Move king_move, Move rook_move, CastlingSide side, Position through_position) -> nil

    def possible?: () -> bool

    def has_through?: () -> bool

    private

    def initialize_required_positions: () -> nil
  end
end

