module Rchess
  class CastlingValidator < MoveValidator
    def validate: (Turn turn, Round round) -> nil

    private

    def figures_present?: (Castling castling) -> bool

    def figures_not_move?: (Castling castling) -> bool

    def places_for_moves_free?: (Castling castling) -> bool

    def figure_present?: (Position position) -> bool

    def get_figure: (Position position) -> Figure
  end
end