class CastlingPattern
  attr_reader king_position: Position

  attr_reader rook_position: Position

  attr_reader king_move_position: Position

  attr_reader rook_move_position: Position

  attr_reader through_position: Position

  attr_reader side: CastlingSide

  def has_through?: () -> bool
end
