@startuml
class Color {
    + {static} String WHITE
    + {static} String BLACK
    + String name

    + Boolean white?()
    + Boolean same?()
    + Color opposite()
}

class Notation {
    + {static} String START_ARRANGEMENT
    + {static} String FIGURES
    + {static} String COORDINATES
    + {static} String NEW_LINE
    + {static} Integer[] NUMBERS
    + {static} String[] LETTERS
    + {static} Integer MIN
    + {static} Integer MAX
    + {static} String WHITE_KING
    + {static} String BLACK_KING
    + {static} String WHITE_QUEEN
    + {static} String BLACK_QUEEN
    + {static} String WHITE_BISHOP
    + {static} String BLACK_BISHOP
    + {static} String WHITE_KNIGHT
    + {static} String BLACK_KNIGHT
    + {static} String WHITE_ROOK
    + {static} String BLACK_ROOK
    + {static} String WHITE_PAWN
    + {static} String BLACK_PAWN

    + {static} Boolean figure?(String notation)
    + {static} Boolean new_line?(String notation)
    + {static} Boolean coordinate?(String notation)
    + {static} Integer[]|nil parse_move(String notation)
}


@enduml