class MoveCollection
  attr_reader figure: Figure

  attr_reader moves: Array[Move]

  def initialize: (Figure figure, ?Array[Move] moves) -> nil

  def check_move: () -> (Move | nil)

  def covered_check_move: () -> (Move | nil)

  def possible_moves: () -> Array[Move]

  def move_by_destination_position: (Position position) -> (Move | nil)

  def has_attack_to_figure?: (Figure figure) -> bool
end
