class FenNotation
  START_ARRANGEMENT: ::String

  FIGURES: ::String

  COORDINATES: ::String

  NUMBERS: ::Array[Integer]

  LETTERS: ::Array[String]

  NEW_LINE: ::String

  WHITE_MOVE: ::String

  BLACK_MOVE: ::String

  KING_SIGNS: ::Array[String]

  QUEEN_SIGNS: ::Array[String]

  BISHOP_SIGNS: ::Array[String]

  KNIGHT_SIGNS: ::Array[String]

  ROOK_SIGNS: ::Array[String]

  PAWN_SIGNS: ::Array[String]

  WHITE_KING: ::String

  BLACK_KING: ::String

  WHITE_QUEEN: ::String

  BLACK_QUEEN: ::String

  WHITE_BISHOP: ::String

  BLACK_BISHOP: ::String

  WHITE_KNIGHT: ::String

  BLACK_KNIGHT: ::String

  WHITE_ROOK: ::String

  BLACK_ROOK: ::String

  WHITE_PAWN: ::String

  BLACK_PAWN: ::String

  def self.figure?: (String notation) -> bool

  def self.new_line?: (String notation) -> bool

  def self.coordinate?: (String notation) -> bool
end
